name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy-to-aws:
    name: Lightsail
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6

      - name: Build Release Binary
        run: cargo build --release --verbose

      - name: Upload to Lightsail
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/release/website, .infisical.json"
          target: "/home/ubuntu/mywebsite/"
          strip_components: 2